### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [nocab-transfer/nocab-desktop#13]
Does this work with Win 7?

Thanks

**Comment by berkekbgz** [comment]
I hadn't tested it yet until you asked. Apparently it doesn't work on the vm.

Due to health problems I could not deal with the project for a few days. When I return to the project in a _few days_, I will check the issue and comment here again. 

Also thanks for your attention!

**Comment by harryray33** [comment]
OK, thank you...

**Comment by berkekbgz** [comment]
Hello, unfortunately the app is not supported on windows 7 (even if it is [supported in the current state of Flutter](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms)). Some packages or code designed for windows 10+ may be causing the app not to work on windows 7. Sorry to say that at the moment nothing additional will be done by me to make the app work on windows 7. Feel free to create a PR if you know how to make it work.
